// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GameCodersToolkit
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string GameCodersToolkitPackage_GuidString = "f45b95a6-2eab-4919-a16f-81bb14ca671f";
        public static Guid GameCodersToolkitPackage_Guid = new Guid(GameCodersToolkitPackage_GuidString);

        public const string DataReferenceFinderCommandSet_GuidString = "4bb2a331-cebe-4cf2-a093-203a5a7f2e95";
        public static Guid DataReferenceFinderCommandSet_Guid = new Guid(DataReferenceFinderCommandSet_GuidString);

        public const string ReferenceResultsToolbarCommandSet_GuidString = "f5e1e0b2-af34-4f67-b8d5-813bf2bc7eda";
        public static Guid ReferenceResultsToolbarCommandSet_Guid = new Guid(ReferenceResultsToolbarCommandSet_GuidString);

        public const string QuickAttachCommandSet_GuidString = "ffea98d0-3d8b-4f5c-be66-0df1926b700a";
        public static Guid QuickAttachCommandSet_Guid = new Guid(QuickAttachCommandSet_GuidString);

        public const string FileTemplateCreatorSet_GuidString = "c614691e-88df-43e1-9d6e-28ca3a32fb57";
        public static Guid FileTemplateCreatorSet_Guid = new Guid(FileTemplateCreatorSet_GuidString);

        public const string AutoDataExposerSet_GuidString = "e7b95c06-f8a5-4c4c-ba8d-d727f865cea6";
        public static Guid AutoDataExposerSet_Guid = new Guid(AutoDataExposerSet_GuidString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int FindDataReferencesEditMenu = 0x0003;
        public const int FindDataReferencesMenuGroupAll = 0x0004;
        public const int FindDataReferencesMenuGroupSpecific = 0x0005;
        public const int FindDataReferencesExtensionsMenu = 0x0006;
        public const int FindDataReferencesExtensionsMenuGroup0 = 0x0007;
        public const int FindDataReferencesExtensionsMenuGroup1 = 0x0008;
        public const int FindDataReferencesExtensionsMenuGroup2 = 0x0009;
        public const int FindGuidReferences_AllLocations = 0x0010;
        public const int FindGuidReferences_Location1 = 0x0020;
        public const int FindGuidReferences_Location2 = 0x0030;
        public const int FindGuidReferences_Location3 = 0x0040;
        public const int FindGuidReferences_Location4 = 0x0050;
        public const int FindGuidReferences_Location5 = 0x0060;
        public const int OpenReferenceResults = 0x1010;
        public const int OpenDataExplorer = 0x1011;
        public const int OpenConfigFile = 0x1020;
        public const int SaveDataReferenceFinderConfig = 0x1030;
        public const int ParseAllDataLocation = 0x1040;
        public const int ClearReferenceDatabase = 0x1050;
        public const int FindGuidReferencesInDatabase = 0x1060;
        public const int ClearAllResults = 0x1100;
        public const int CollapseAllResults = 0x1200;
        public const int ExpandAllResults = 0x1300;
        public const int FilterResults = 0x1400;
        public const int ReferenceResultsToolbar = 0x1010;
        public const int ReferenceResultsToolbarGroup0 = 0x1020;
        public const int ReferenceResultsToolbarGroup1 = 0x1030;
        public const int ReferenceResultsToolbarGroup2 = 0x1040;
        public const int QuickAttachToolbar = 0x0010;
        public const int QuickAttachToolbarGroup = 0x0020;
        public const int QuickAttachCommand = 0x0100;
        public const int QuickAttachSelector = 0x0200;
        public const int QuickAttachSelectorListCmd = 0x0300;
        public const int CreateFileFromTemplateExtensionsMenu = 0x0010;
        public const int CreateFileFromTemplate = 0x0020;
        public const int OpenTemplateFileCreatorConfigExtensionsMenu = 0x0030;
        public const int OpenTemplateFileCreatorConfig = 0x0040;
        public const int FileTemplateCreatorExtensionsMenuGroup = 0x0007;
        public const int AutoDataExposerSubMenu = 0x1001;
        public const int AutoDataExposerSubMenuGroup = 0x1000;
        public const int AutoDataExposerContextMenuGroup = 0x1020;
        public const int ExposeToDataCommand = 0x2000;
        public const int AutoDataExposerExtensionsMenuGroup = 0x0007;
        public const int OpenAutoDataExposerCreatorConfigExtensionsMenu = 0x0030;
        public const int OpenAutoDataExposerConfig = 0x0040;
    }
}