// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GameCodersToolkit
{
    internal sealed partial class Vsix
    {
        public const string Id = "GameCodersToolkit.49757eef-0bb3-49a6-a9df-633cdee57064";
        public const string Name = "GameCodersToolkit";
        public const string Description = @"Find references of your code in data files.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Henning Ax";
        public const string Tags = "";
    }
}
