// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DataReferenceFinder
{
	internal sealed partial class Vsix
	{
		public const string Id = "BasicFindGuidCommand.49757eef-0bb3-49a6-a9df-633cdee57064";
		public const string Name = "BasicFindGuidCommand";
		public const string Description = @"Empty VSIX Project.";
		public const string Language = "en-US";
		public const string Version = "1.0";
		public const string Author = "Henning Ax";
		public const string Tags = "";
	}
}
