// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DataReferenceFinder
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string DataReferenceFinderPackage_GuidString = "f45b95a6-2eab-4919-a16f-81bb14ca671f";
        public static Guid DataReferenceFinderPackage_Guid = new Guid(DataReferenceFinderPackage_GuidString);

        public const string DataReferenceFinderCommandSet_GuidString = "4bb2a331-cebe-4cf2-a093-203a5a7f2e95";
        public static Guid DataReferenceFinderCommandSet_Guid = new Guid(DataReferenceFinderCommandSet_GuidString);

        public const string ReferenceResultsToolbarCommandSet_GuidString = "f5e1e0b2-af34-4f67-b8d5-813bf2bc7eda";
        public static Guid ReferenceResultsToolbarCommandSet_Guid = new Guid(ReferenceResultsToolbarCommandSet_GuidString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int FindDataReferencesToolsGroup = 0x0001;
        public const int FindDataReferencesViewGroup = 0x0002;
        public const int FindDataReferencesEditMenu = 0x0003;
        public const int FindDataReferencesMenuGroupAll = 0x0004;
        public const int FindDataReferencesMenuGroupSpecific = 0x0005;
        public const int FindGuidReferences_AllLocations = 0x0010;
        public const int FindGuidReferences_Location1 = 0x0020;
        public const int FindGuidReferences_Location2 = 0x0030;
        public const int FindGuidReferences_Location3 = 0x0040;
        public const int FindGuidReferences_Location4 = 0x0050;
        public const int FindGuidReferences_Location5 = 0x0060;
        public const int OpenReferenceResults = 0x1010;
        public const int SaveDataReferenceFinderConfig = 0x1030;
        public const int ClearAllResults = 0x1100;
        public const int CollapseAllResults = 0x1200;
        public const int FilterResults = 0x1300;
        public const int ReferenceResultsToolbar = 0x1010;
        public const int ReferenceResultsToolbarGroup0 = 0x1020;
        public const int ReferenceResultsToolbarGroup1 = 0x1030;
        public const int ReferenceResultsToolbarGroup2 = 0x1040;
    }
}