// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GameCodersToolkit
{
    internal sealed partial class Vsix
    {
        public const string Id = "GameCodersToolkit_2019.02cbee57-bbf7-4114-8359-50f1d8833ad8";
        public const string Name = "GameCodersToolkit_2019";
        public const string Description = @"Find references of your code in data files.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Henning Ax";
        public const string Tags = "";
    }
}
